spring.application.name=Cache Evict

# ======== CONFIGURARE POSTGRESQL ========
spring.datasource.url=jdbc:postgresql://localhost:5432/cache_demo_db
spring.datasource.username=postgres
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver

# ======== CONFIGURARE JPA (Hibernate) ========
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# ======== Prometheus ==========
management.endpoints.web.exposure.include=metrics,health,prometheus

# ======= Storage =========
app.l2.cache-dir=./cache_l2_storage
app.l2.max-files=20